export const products = [
  {
    id: 1,
    images: [
      "https://images.unsplash.com/photo-1521577352947-9bb58764b69a",
      "https://images.unsplash.com/photo-1521577352947-9bb58764b69a",
      "https://images.unsplash.com/photo-1521577352947-9bb58764b69a",
    ],
    title: "Men's Cotton T-Shirt",
    isFavorite: true,
    ratings: 4.5,
    price: 19.99,
    brandName: "FashionMax",
    description: "Soft and breathable cotton t-shirt for casual wear.",
    colors: ["Yellow", "Purple", "Gray"],
    sizes: ["Small", "X-Small", "Large", "X-Large"],
    quantity: 1,
    reviews: [
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
      {
        user: "John Doe",
        comment: "Very comfortable and fits perfectly!",
        rating: 5,
      },
    ],
  },
  {
    id: 2,
    images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
    title: "Slim Fit Jeans",
    isFavorite: false,
    ratings: 4,
    price: 39.99,
    brandName: "DenimStyle",
    description: "Stylish slim fit jeans with stretchable fabric.",
    colors: ["Orange", "Black", "Pink", "White"],
    sizes: ["Medium", "Large", "X-Large"],
    quantity: 1,
    reviews: [
      {
        user: "Alice",
        comment: "Good quality, but runs a bit small.",
        rating: 4,
      },
    ],
  },
  {
    id: 3,
    images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
    title: "Polarized Sunglasses",
    isFavorite: true,
    ratings: 4.7,
    price: 29.99,
    brandName: "ShadeX",
    description: "UV protection polarized sunglasses for men and women.",
    colors: ["Black", "White", "Gray"],
    sizes: ["Medium", "Large"],
    quantity: 1,
    reviews: [
      {
        user: "Mike",
        comment: "Great for sunny days and driving!",
        rating: 5,
      },
    ],
  },
  {
    id: 4,
    images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
    title: "Men's Hoodie",
    isFavorite: false,
    ratings: 3.5,
    price: 49.99,
    brandName: "CozyWear",
    description: "Warm and stylish hoodie for cold weather.",
    colors: ["Black", "Gray", "Navy"],
    sizes: ["Medium", "Large", "X-Large", "Small"],
    quantity: 1,
    reviews: [
      {
        user: "Steve",
        comment: "Very comfortable and warm!",
        rating: 5,
      },
    ],
  },
  {
    id: 5,
    images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
    title: "Women's Yoga Leggings",
    isFavorite: true,
    ratings: 4.8,
    price: 24.99,
    brandName: "ActiveFit",
    description: "Stretchable and comfortable leggings for workouts.",
    colors: ["Black", "Pink", "Blue"],
    sizes: ["X-Small", "Medium", "Large"],
    quantity: 1,
    reviews: [
      {
        user: "Sophie",
        comment: "Perfect fit and very comfortable!",
        rating: 5,
      },
    ],
  },
  {
    id: 6,
    images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
    title: "Men's Formal Shirt",
    isFavorite: false,
    ratings: 4.4,
    price: 34.99,
    brandName: "EliteWear",
    description: "Premium cotton formal shirt for office and events.",
    colors: ["White", "Blue", "Gray"],
    sizes: ["Medium"],
    quantity: 1,
    reviews: [
      {
        user: "David",
        comment: "Good quality and fits well.",
        rating: 4,
      },
    ],
  },
  // {
  //   id: 7,
  //   images: ["https://images.unsplash.com/photo-1536148935331-408321065b18"],
  //   title: "Sports Tracksuit",
  //   isFavorite: true,
  //   ratings: 4.7,
  //   price: 59.99,
  //   brandName: "SportFlex",
  //   description: "Breathable and flexible tracksuit for running and training.",
  //   colors: ["Black", "Red", "Gray"],
  //   sizes: ["M", "L", "XL"],
  //   quantity: 1,
  //   reviews: [
  //     {
  //       user: "Olivia",
  //       comment: "Great for workouts and comfortable to wear!",
  //       rating: 5,
  //     },
  //   ],
  // },
  // {
  //   id: 8,
  //   images: ["https://images.unsplash.com/photo-1536148935331-408321065b18"],
  //   title: "Women's Denim Jacket",
  //   isFavorite: false,
  //   ratings: 4.5,
  //   price: 45.99,
  //   brandName: "TrendStyle",
  //   description: "Fashionable denim jacket for women.",
  //   colors: ["Blue", "Black"],
  //   sizes: ["S", "M", "L"],
  //   quantity: 1,
  //   reviews: [
  //     {
  //       user: "Emma",
  //       comment: "Looks amazing with any outfit!",
  //       rating: 5,
  //     },
  //   ],
  // },
  // {
  //   id: 9,
  //   images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
  //   title: "Cargo Pants",
  //   isFavorite: true,
  //   ratings: 3,
  //   price: 32.99,
  //   brandName: "OutdoorGear",
  //   description: "Durable and comfortable cargo pants with multiple pockets.",
  //   colors: ["Green", "Black", "Khaki"],
  //   sizes: ["M", "L", "XL"],
  //   quantity: 1,
  //   reviews: [
  //     {
  //       user: "Lucas",
  //       comment: "Perfect for outdoor activities!",
  //       rating: 4,
  //     },
  //   ],
  // },
  // {
  //   id: 10,
  //   images: ["https://images.unsplash.com/photo-1521577352947-9bb58764b69a"],
  //   title: "Men's Leather Belt",
  //   isFavorite: false,
  //   ratings: 4.6,
  //   price: 19.99,
  //   brandName: "ClassicWear",
  //   description: "High-quality leather belt with adjustable fit.",
  //   colors: ["Black", "Brown"],
  //   sizes: ["M", "L"],
  //   quantity: 1,
  //   reviews: [
  //     {
  //       user: "Daniel",
  //       comment: "Strong and stylish!",
  //       rating: 5,
  //     },
  //   ],
  // },
];
